RezerevasyonSistem/Areas/Admin/Controllers/HomeController.cs
using RezervasyonSistem.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RezerevasyonSistem.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        private RezervasyonSistemContext _context;
        public HomeController()
        {
            _context = new RezervasyonSistemContext();

            if (_context.Odalar.Count()<1)
            {
                var yeniOda = new Oda
                {
                    CocukIcinUygunMu = false,
                    Fiyat = 100,
                    KapiNo = "Z01",
                    KisiSayisi = 2
                };
                _context.Odalar.Add(yeniOda);
                _context.SaveChanges();
            }
        }
        // GET: Admin/Home
        public ActionResult Index()
        {
            

            return View();
        }
        public ActionResult Profil()
        {
            return View();
        }
        public ActionResult Musteriler()
        {
            return View();
        }
    }
}

RezerevasyonSistem/Areas/Admin/Controllers/OdaController.cs
using RezervasyonSistem.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RezerevasyonSistem.Areas.Admin.Controllers
{
    public class OdaController : Controller
    {
        // GET: Admin/Oda
        public RezervasyonSistemContext _context= new RezervasyonSistemContext();
        public OdaController()
        {
            //_context = new RezervasyonSistemContext();
        }
        public ActionResult Yeni()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Yeni(Oda oda)
        {
            _context.Odalar.Add(oda);
            var result=_context.SaveChanges();
            var mesaj = result > 0 ? "Başarı ile kaydedildi" : "Kayıt yapılamadı";
            TempData["Mesaj"] = mesaj;
            return View();
        }
        public ActionResult OdaListe()
        {
            List<Oda> odalar=_context.Odalar.ToList();
            
              
                        
            return View(odalar);
        }
        [HttpPost]
        public JsonResult OdaDetay(int id)
        {
            var seciliOda = _context.Odalar.FirstOrDefault(o => o.Id == id);
            return Json(seciliOda);
        }
    }
}

RezerevasyonSistem/Controllers/DefaultController.cs
using RezervasyonSistem.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RezerevasyonSistem.Controllers
{
    public class DefaultController : Controller
    {
        private RezervasyonSistemContext _context;
        public DefaultController()
        {
            //Dependency Injection
            _context = new RezervasyonSistemContext();
        }
        // GET: Default
        public ActionResult Index()
        {
            var odalar = _context.Odalar.ToList();
            ViewBag.Title = "Birşeyler";
            return View(odalar);
        }

        public ActionResult RezervasyonYap(int? id)
        {
            if (id == null) return RedirectToAction("Index");
            var seciliOda = _context.Odalar.FirstOrDefault(o => o.Id == id);
            if (seciliOda == null) return RedirectToAction("Index");
            return View(seciliOda);
        }
    }
}

RezerevasyonSistem/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPageAdmin.cshtml";
}



    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Rezervasyon Sistemi
            <small>Giriş Ekranı</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Anasayfa</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3>150</h3>
                        <p>New Orders</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>53<sup style="font-size: 20px">%</sup></h3>
                        <p>Bounce Rate</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-yellow">
                    <div class="inner">
                        <h3>44</h3>
                        <p>User Registrations</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-person-add"></i>
                    </div>
                    <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-red">
                    <div class="inner">
                        <h3>65</h3>
                        <p>Unique Visitors</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                    </div>
                    <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        
        <!-- /.row (main row) -->
    </section>
    <!-- /.content -->

RezerevasyonSistem/Areas/Admin/Views/Home/Musteriler.cshtml
@{
    ViewBag.Title = "Musteriler";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Musteriler</h2>

RezerevasyonSistem/Areas/Admin/Views/Home/Profil.cshtml
@{
    ViewBag.Title = "Profil";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Profil</h2>

RezerevasyonSistem/Areas/Admin/Views/Oda/OdaListe.cshtml
@using RezervasyonSistem.Data.Models
@model IEnumerable<Oda>
@{
    ViewBag.Title = "OdaListe";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPageAdmin.cshtml";
}
@section extraStyle{
    <link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
}
<table class="table table-hover table-bordered table-striped" id="tablo">
    <thead>
        <tr>
            <th>Id</th>
            <th>Kapi No</th>
            <th>Kisi Sayisi</th>
            <th>Fiyat</th>
            <th>Çocuk İçin Uygun Mu</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var oda in Model)
        {
            <tr>
                <td>@oda.Id</td>
                <td>@oda.KapiNo</td>
                <td>@oda.KisiSayisi</td>
                <td>@oda.Fiyat</td>
                <td>@(oda.CocukIcinUygunMu ? "Uygun" : "Değil")</td>
                <td>
                    <button type="button" class="btn btn-default btn-xs" id="detay-@oda.Id" onclick="DetayGoster(this)">Detaylar</button>
                    <button type="button" class="btn btn-xs btn-danger" id="sil-@oda.Id" onclick="Sil(this)">Sil</button>
                </td>
            </tr>
        }
    </tbody>
</table>


<!-- Modal -->
<div class="modal fade" id="odaModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Oda özellikleri</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="col-md-4">
                        Kapı No
                    </div>
                    <div class="col-md-8">
                        <input type="text" id="txbKapiNo" class="form-control" placeholder="Kapı no" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        Kişi Sayısı
                    </div>
                    <div class="col-md-8">
                        <input type="text" id="txbKisiSayisi" class="form-control" placeholder="Kişi Sayısı" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        Fiyat
                    </div>
                    <div class="col-md-8">
                        <input type="text" id="txbFiyat" class="form-control" placeholder="Fiyat" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        Çocuk için Uygun Mu
                    </div>
                    <div class="col-md-8">
                        <input type="checkbox" id="chkCocuk" />
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapats</button>
                <button type="button" class="btn btn-primary">Kaydet</button>
            </div>
        </div>
    </div>
</div>
@section extraScript{
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
        $().ready(function () {
            $('#tablo').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json"
                }
            });

        });
        function DetayGoster(element) {

            var id = $(element).attr('id'); //detay-1
            var elementId = id.substr(6);
            console.log(elementId);
            var gonderilen = {};
            gonderilen.Id = elementId;
            $.ajax({
                url: '@Url.Action("OdaDetay","Oda")',
                type: 'post',
                dataType: 'json',
                contentType: 'application/json;charset=utf-8',
                data: JSON.stringify(gonderilen),
                success: function (gelenDeger) {
                    console.log(gelenDeger);
                    $('#odaModal').modal('show');
                    $('#txbKapiNo').val(gelenDeger.KapiNo);
                    $('#txbKisiSayisi').val(gelenDeger.KisiSayisi);
                    $('#txbFiyat').val(gelenDeger.Fiyat);
                    gelenDeger.CocukIcinUygunMu == true ? $('#chkCocuk').prop('checked', true) : $('#chkCocuk').prop('checked', false);
                },
                error: function (err) {
                    console.error(err.statusText);
                }
            });
        }
    </script>
}

RezerevasyonSistem/Areas/Admin/Views/Oda/Yeni.cshtml
@model RezervasyonSistem.Data.Models.Oda
@{
    ViewBag.Title = "Yeni";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPageAdmin.cshtml";
}
@{
    var mesaj = TempData["Mesaj"];
    if (mesaj != null)
    {
        <div class="pad margin no-print">
            <div class="callout callout-info" style="margin-bottom: 0!important;">
                <h4><i class="fa fa-info"></i> Not:</h4>
                @mesaj
            </div>
        </div>
    }
}

<div class="container-fluid">
    <!-- Input addon -->
    <div class="col-md-6">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Yeni Oda</h3>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="box-body">

                    <div class="input-group">
                        <span class="input-group-addon">₺</span>
                        @*<input type="text" class="form-control" placeholder="Fiyat">*@
                        @Html.TextBoxFor(m => m.Fiyat, htmlAttributes: new { @class = "form-control", placeholder = "Fiyat" })
                        <span class="input-group-addon">.00</span>
                    </div>
                    <br />
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-users"></i></span>
                        @*<input type="text" class="form-control" placeholder="Kişi Sayısı">*@
                        @Html.TextBoxFor(m => m.KisiSayisi, htmlAttributes: new { @class = "form-control", placeholder = "Kişi sayısı" })
                    </div>

                    <br />
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-sticky-note"></i></span>
                        @*<input type="text" class="form-control" placeholder="Kapı No">*@
                        @Html.TextBoxFor(m => m.KapiNo, htmlAttributes: new { @class = "form-control", placeholder = "Kapı No" })
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    @*Çocuk Var mı?<input type="checkbox">*@
                                    Çocuk Var mı? @Html.CheckBoxFor(m => m.CocukIcinUygunMu)
                                </span>
                            </div>
                            <!-- /input-group -->
                        </div>
                        <!-- /.col-lg-6 -->
                        <!-- /.col-lg-6 -->
                    </div>
                    <!-- /.row -->
                    <!-- /input-group -->
                    <br />
                    <div class="input-group input-group-sm">
                        <button type="submit" class="btn btn-md btn-info">Kaydet</button>
                    </div>
                    <!-- /input-group -->
                </div>
                <!-- /.box-body -->
            }
        </div>
        <!-- /.box -->
    </div>
</div>

RezerevasyonSistem/Views/Default/Index.cshtml
@using RezervasyonSistem.Data.Models
@model IEnumerable<Oda>
@{
    
    Layout = "~/Views/Shared/_LayoutPageAna.cshtml";
    var sayac = 0;
}
<div class="container-fluid">
    <div class="pad margin no-print">
        <div class="callout callout-info" style="margin-bottom: 0!important;">
            <h4><i class="fa fa-info"></i> Not:</h4>
            Mevcut odalarımız aşağıda listelenmektedir.
        </div>
    </div>
    <section class="content">
        <div class="row">

            @foreach (var oda in Model)
            {
                <div class="col-md-3">
                    <!-- Profile Image -->
                    <div class="box box-primary">
                        <div class="box-body box-profile">

                            <div>
                                <div class="box box-solid">
                                    <div class="box-body">
                                        <div id="carousel-example-generic-@oda.Id"  class="carousel slide" data-ride="carousel">
                                            <ol class="carousel-indicators">
                                              
                                                @for (int i=0; i < 3; i++)
                                                {
                                                    <li data-target="#carousel-example-generic" data-slide-to="@sayac" class=""></li>
                                                    sayac++;
                                                }

                                               
                                            </ol>
                                            <div class="carousel-inner">
                                                <div class="item active">
                                                    <img src="http://placehold.it/900x500/39CCCC/ffffff&text=I+Love+Bootstrap" alt="First slide">
                                                    <div class="carousel-caption">
                                                        First Slide
                                                    </div>
                                                </div>
                                                <div class="item">
                                                    <img src="http://placehold.it/900x500/3c8dbc/ffffff&text=I+Love+Bootstrap" alt="Second slide">
                                                    <div class="carousel-caption">
                                                        Second Slide
                                                    </div>
                                                </div>
                                                <div class="item">
                                                    <img src="http://placehold.it/900x500/f39c12/ffffff&text=I+Love+Bootstrap" alt="Third slide">
                                                    <div class="carousel-caption">
                                                        Third Slide
                                                    </div>
                                                </div>
                                            </div>
                                            <a class="left carousel-control" href="#carousel-example-generic-@oda.Id" data-slide="prev">
                                                <span class="fa fa-angle-left"></span>
                                            </a>
                                            <a class="right carousel-control" href="#carousel-example-generic-@oda.Id" data-slide="next">
                                                <span class="fa fa-angle-right"></span>
                                            </a>
                                        </div>
                                    </div>
                                    <!-- /.box-body -->
                                </div>
                                <!-- /.box -->
                            </div>



                            <ul class="list-group list-group-unbordered">
                                <li class="list-group-item">
                                    <b>Fiyat</b> <a class="pull-right">@oda.Fiyat₺</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Kişi Sayısı</b> <a class="pull-right">@oda.KisiSayisi</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Çocuk</b> <a class="pull-right">@(oda.CocukIcinUygunMu?"Uygun":"Uygun Değil")</a>
                                </li>
                            </ul>
                            <a href="@Url.Action("RezervasyonYap","Default",new{id=oda.Id})" class="btn btn-primary btn-block"><b>Rezervasyon Yap</b></a>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                    <!-- About Me Box -->
                    <!-- /.box -->
                </div>
            }

            <!-- /.col -->

        </div>
        <!-- /.row -->
    </section>

</div>


@section extraScript{
    <script>
        $().ready(function(){
            $('.carousel').carousel({
                interval: 10000,
                keyboard:true
            });
        });

    </script>
}

RezerevasyonSistem/Views/Default/RezervasyonYap.cshtml
@using RezervasyonSistem.Data.Models
@model Oda
@{
    ViewBag.Title = "RezervasyonYap";
    Layout = "~/Views/Shared/_LayoutPageAna.cshtml";
}

<h2>RezervasyonYap</h2>
<ul>
    <li>@Model.Id</li>
    <li>@Model.KapiNo</li>
    <li>@Model.KisiSayisi</li>
    <li>@Model.Fiyat ₺</li>
</ul>

RezerevasyonSistem/Views/Shared/_LayoutPageAna.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="../../Assets/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../Assets/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="../../Assets/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../Assets/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="../../Assets/dist/css/skins/_all-skins.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <script src="../../Assets/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="../../Assets/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="../../Assets/bower_components/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="../../Assets/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="../../Assets/dist/js/demo.js"></script>
    @RenderSection("extraScript", required: false)
</body>
</html>